---
- fail:
    msg: "bailing out, this role requires 'crowdsec_enroll_key'  and 'crowdsec_enroll_name' to be defined." 
  when:
  - crowdsec_enroll_key is not defined
  - crowdsec_enroll_name is not defined
-
  import_tasks: debian.yml
  when: (ansible_facts['distribution'] == "Debian")
-
  import_tasks: rhel.yml
  when: (ansible_facts['os_family'] == "RedHat")
-
